name: Compile LaTeX to PDF

on:
  push:
    paths:
      - '**.tex'  # Triggers the action when any .tex file is pushed
  pull_request:
    paths:
      - '**.tex'  # Triggers the action when any .tex file is modified in a PR

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for compiling LaTeX
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install LaTeX
      - name: Install LaTeX
        run: sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      # Step 3: Compile LaTeX to PDF
      - name: Compile LaTeX to PDF
        run: pdflatex OwenEnestvedtResume.tex  

      # Step 4: Upload PDF as artifact
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-latex-pdf
          path: OwenEnestvedtResume.pdf  # PDF output file

      # Step 5: Update README.md with the link to the PDF
      - name: Update README.md with PDF link
        run: |
          # Ensure the PDF file is uploaded and available in the repository
          echo "### Rendered LaTeX Output" >> README.md
          echo "[View my Resume in PDF](https://github.com/${GITHUB_REPOSITORY}/raw/${GITHUB_SHA}/OwenEnestvedtResume.pdf)" >> README.md

      # Step 6: Commit and push changes to README.md
      - name: Commit and push changes to README.md
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with link to compiled PDF"
          git push origin HEAD:main  
