name: Compile LaTeX to PDF

on:
  push:
    paths:
      - '**.tex'  # Triggers the action when any .tex file is pushed
  pull_request:
    paths:
      - '**.tex'  # Triggers the action when any .tex file is modified in a PR

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for compiling LaTeX
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install LaTeX
      - name: Install LaTeX
        run: sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra

      # Step 3: Delete the old resume PDF if it exists
      - name: Delete old resume PDF (if exists)
        run: |
          if [ -f OwenEnestvedtResume.pdf ]; then
            rm OwenEnestvedtResume.pdf
            echo "Old PDF deleted."
          else
            echo "No old PDF found."
          fi

      # Step 4: Compile LaTeX to PDF
      - name: Compile LaTeX files to PDF
        run: pdflatex OwenEnestvedtResume.tex

      # Step 5: Upload the newly compiled PDF as an artifact
      - name: Upload new resume PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-latex-pdf
          path: OwenEnestvedtResume.pdf  # The new PDF file to upload

